### ISSUE TITLE
Support for later/latest version of java.jdbc?

### ISSUE THREAD

**Issue by dcj** [duelinmarkers/clj-record#13]
I use a combination of Clojure DB libraries to access my DBs.
Right now clj-record is the only library that I can't make work with java.jdbc version 0.2.2.

clj-record will build against 0.2.2, but it fails to run.

I would very much like to have a version that would work with 0.2.2

**Comment by duelinmarkers** [comment]
What do you mean when you say it will build against 0.2.2 but fails to run?

I've just cut a 1.1.3 release that depends on the latest clojure.java.jdbc. Does that work for you?
