### ISSUE TITLE
IllegalStateException resultset-seq already refers to: #'clojure.java.jdbc/resultset-seq in namespace

### ISSUE THREAD

**Issue by juliangamble** [duelinmarkers/clj-record#17]
I've got the following in my project.clj

(defproject project_clj-record "0.1.0-SNAPSHOT"
  :description "FIXME: write description"
  :url "http://example.com/FIXME"
  :license {:name "Eclipse Public License"
            :url "http://www.eclipse.org/legal/epl-v10.html"}
  :dependencies [
                 [clj-record "1.1.4"]
                 [postgresql/postgresql "8.4-702.jdbc4"] ])

When I run the following in a counterclockwise repl:

(ns project-clj-record.BugTableTest
  (:require clj-record.boot))

I get:

IllegalStateException resultset-seq already refers to: #'clojure.java.jdbc/resultset-seq in namespace: clj-syd-bug-tracker-clj-record.BugTableTest  clojure.lang.Namespace.warnOrFailOnReplace (Namespace.java:88)

This appears to be a bug.

**Comment by duelinmarkers** [comment]
I don't have counterclockwise, but in a brand new project with your project.clj and a src/project_clj_record/BugTableTest.clj with the given content, I run `lein repl` (with lein 2) and do the following without any error.

```
(require 'project-clj-record.BugTableTest)
```

Just to be sure things seem to be working, I added a `defn` to that empty namespace, and I can call the `fn` fine, both from outside after requiring the namespace.

So I don't think this is a bug in clj-record. Can you try the same steps to see if there's some other difference between my environment and yours?

Here are some thoughts:

That error message is similar to what you get when you `use` or `require...refer` some var with the same name as something your namespace already refers to. The conflict may be between `clojure.core/resultset-seq` and `clojure.java.jdbc/resultset-seq`. Normally when you hit that sort of conflict, it's not an error, and the message ends with something like ", being replaced by: #'clojure.java.jdbc/resultset-seq". clj-record does not `use` or `require...refer` the `clojure.java.jdbc` namespace anywhere, but I wonder if counterclockwise is doing something funky.

I think it's unusual to use the `ns` macro from a repl. You may be into territory the counterclockwise developers haven't tested for.
