### ISSUE TITLE
It would be useful if dashes in keys were replaced with underscores

### ISSUE THREAD

**Issue by edoloughlin** [duelinmarkers/clj-record#6]
clj-record seems to put map key names directly into SQL. This means I have to be careful with keys and use, e.g., :user_id instead of :user-id if there's a chance the key will be used by clj-record. It would be useful if there was an automatic conversion to underscores before generating SQL.

**Comment by duelinmarkers** [comment]
Definitely agreed. I'm trying to get other patches people have submitted in, then planning to add this, then planning to make bigger changes.

**Comment by duelinmarkers** [comment]
If anyone wants to add this as a feature (without changing the default behavior) I'm happy to accept a pull request, but I'm not longer planning to add this myself.

**Comment by duelinmarkers** [comment]
Closing as the project is now deprecated and hopefully not in use.
