### ISSUE TITLE
Can I use 'rand' in a :before-save function?

### ISSUE THREAD

**Issue by edoloughlin** [duelinmarkers/clj-record#8]
If I use `rand` to assign values in a `:before-save` function then the map I get back from `create` is different to what's in the database. Is this supported?

Also posted to http://stackoverflow.com/questions/6862066

**Comment by duelinmarkers** [comment]
That's definitely not the intended behavior. Could be a bug. I'll have a
look this evening and get back to you.

-- typed with my thumbs
On Jul 28, 2011 12:14 PM, "edoloughlin" <
reply@reply.github.com>
wrote:

**Comment by duelinmarkers** [comment]
I've just added these tests, and they pass for me.

(defdbtest before-save-only-gets-called-once-on-create-testing-with-inc
  (restoring-ref (manufacturer/model-metadata)
    (callbacks/add-callback "manufacturer" :before-save #(assoc %
:grade (inc (:grade %))))
    (let [m (manufacturer/create (valid-manufacturer-with {:grade 1}))](is %28= 2 %28m :grade%29%29))))

(defdbtest before-save-only-gets-called-once-on-create-testing-with-rand
  (restoring-ref (manufacturer/model-metadata)
    (callbacks/add-callback "manufacturer" :before-save #(assoc %
:grade (\* 100 (rand))))
    (let [m (manufacturer/create (valid-manufacturer-with {:grade nil}))](is %28= %28manufacturer/get-record %28m :id%29%29
             m%29))))

In the first I'm defining a before-save callback that increments the
:grade by one. I'm calling create with a :grade of 1 and getting back
a record with a grade of 2. In the second I'm closer to your case,
where I use rand and see that the value I get back from create matches
what I read from the DB.

Is it possible you have some other callback defined (like an after-load)?

On Thu, Jul 28, 2011 at 6:06 PM, John D. Hume duelin.markers@gmail.com wrote:

> That's definitely not the intended behavior. Could be a bug. I'll have a
> look this evening and get back to you.
> 
> -- typed with my thumbs
> 
> On Jul 28, 2011 12:14 PM, "edoloughlin"
> reply@reply.github.com
> wrote:
> 
> > If I use `rand` to assign values in a :before-save function then the map I
> > get back from `create` is different to what's in the database. Is this
> > supported?
> > 
> > Also posted to http://stackoverflow.com/questions/6862066
> > 
> > ## 
> > 
> > Reply to this email directly or view it on GitHub:
> > https://github.com/duelinmarkers/clj-record/issues/8

## 

http://elhumidor.blogspot.com/

**Comment by duelinmarkers** [comment]
These tests are available in the repo, if you want to experiment with them and try to recreate your issue.
