### ISSUE TITLE
Test failures when using mysql driver

### ISSUE THREAD

**Issue by vinothkr** [duelinmarkers/clj-record#9]
The tests dont roll back the data which it created. Its really weird that it doesnt happen when i switched back to derby driver.

**Comment by duelinmarkers** [comment]
You'll need to configure MySQL to use the InnoDB engine by default. Out of the box it defaults to MyISAM, which doesn't support transactions.

A patch to script this (or even just fail if the engine is MyISAM) would be gratefully accepted.

**Comment by vinothkr** [comment]
Oh i get it..

The clojure.java.jdbc (not clojure.contrib.sql) of clojure-contrib 1.3.0 extended the create table with an option of providing :table-spec in which we can specify the engine that has to be use for mysql. But the clojure-contrib has revamped the whole api set. So upgrading clojure and contrib version can make the job easier for this. Which eventually has to be done.
